### ISSUE TITLE
Unable to compile TabProps or Spitfire from source

### ISSUE THREAD

**Issue by mameehan5** [sandialabs/Spitfire#27]
Hi Mike, 

I am having a few issues trying to build TabProps and Spitfire from source. 

First, for TabProps, I ran `make install` and it failed:
```
tabprops/prepro/mixmdl/BetaMixMdl.h: No such file or directory
 #include <tabprops/prepro/mixmdl/BetaMixMdl.h>
```

Second, for Spitfire, after creating my own fork, I tried `python3 setup.py install` and it failed:
```
Traceback (most recent call last):
  File "/home/mameeha/research/spitfire/Spitfire/setup.py", line 75, in <module>
    c.write_gitinfo()
  File "/home/mameeha/research/spitfire/Spitfire/setup.py", line 50, in write_gitinfo
    latest_tag = tags[-1]
                 ~~~~^^^^
IndexError: list index out of range
```
which is definitely a result not having any previous commits on my fork.

Third, for Spitfire, using the normal code base, I tried `python3 setup.py install` and it failed with a bunch of errors. Here are a few:
```
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from src/spitfire/griffon/griffon.cpp:832:0:
```
```
src/spitfire/griffon/include/combustion_kernels.h:151:17: error: ‘array’ is not a member of ‘std’
     std::vector<std::array<double, NCP>> coefficients;
```
```
src/spitfire/griffon/include/combustion_kernels.h:275:12: error: ‘constexpr’ does not name a type
     static constexpr int NCP = NCPn;
```

Any idea what could be causing these issues? Thanks!
Mike Meehan

**Comment by michael-a-hansen** [comment]
@mameehan5 sorry I missed your message on this. I had a github-specific folder in my email but the new Outlook closed the folder it lived in, so I didn't see anything in there for a while :p.

I just pushed some fixes for this, according to our conversation the other day.
